from pydantic import BaseModel, Field
from typing import List


class SetUpProjectStructureOutput(BaseModel):
    """Pydantic model for set_up_project_structure node outputs."""
    project_name: str = Field(..., description="The name of the project")
    directory_structure: List[str] = (
        Field(..., description="A list of key directories in the project structure")
    )
    file_list: List[str] = (
        Field(..., description="A list of key files in the project structure")
    )
    is_valid: bool = (
        Field(..., description="Whether the project structure is valid")
    )


class WriteProductListingLogicOutput(BaseModel):
    """Pydantic model for write_product_listing_logic node outputs."""
    product_list: List[str] = Field(..., description="List of product names")
    product_descriptions: List[str] = (
        Field(..., description="List of product descriptions")
    )
    product_prices: List[float] = (
        Field(..., description="List of product prices")
    )
    is_product_listing_successful: bool = (
        Field(..., description="Whether the product listing logic was successfully implemented")
    )


def write_product_listing_logic(set_up_project_structure_input: SetUpProjectStructureOutput, **kwargs) -> WriteProductListingLogicOutput:
    """
    Fetches product data and returns structured lists of names, descriptions,
    and prices.

    Parameters
    ----------
    project_name : str
        Name of the shopping app project.
    directory_structure : List[str]
        List of key directories in the project structure.
    file_list : List[str]
        List of key files in the project structure.
    is_valid : bool
        Validity flag of the project structure generated by
        set_up_project_structure.

    Returns
    -------
    dict
        A dictionary containing product_list, product_descriptions,
        product_prices, and is_product_listing_successful.

    Raises
    ------
    ValueError
        Raised when the project structure is invalid (is_valid is False).

    Examples
    --------
    >>> output = write_product_listing_logic(
    ...     project_name='ShopApp',
    ...     directory_structure=['src', 'tests'],
    ...     file_list=['main.py', 'utils.py'],
    ...     is_valid=True
    >>> )
    {
      'product_list': [],
      'product_descriptions': [],
      'product_prices': [],
      'is_product_listing_successful': True
    }

    >>> output = write_product_listing_logic(
    ...     project_name='ShopApp',
    ...     directory_structure=['src', 'tests'],
    ...     file_list=['main.py', 'utils.py'],
    ...     is_valid=True
    >>> )
    {
      'product_list': ['T-Shirt', 'Jeans'],
      'product_descriptions': ['Cotton T-Shirt', 'Denim Jeans'],
      'product_prices': [19.99, 49.99],
      'is_product_listing_successful': True
    }

    """
    return WriteProductListingLogicOutput(
        product_list=[],
        product_descriptions=[],
        product_prices=[],
        is_product_listing_successful=False,
    )